services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant
    command: >
      sh -c "uvicorn app.main:app --host ${HOST} --port ${PORT}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./storage_data:/code/storage
      - ./app/migrations/versions:/code/app/migrations/versions

volumes:
  postgres_data:
  qdrant_data:
  storage_data: